### ISSUE TITLE
GebSampleSpec doesn't run due to geb.driver.DriverCreationException

### ISSUE THREAD

**Issue by jacattau** [AOEpeople/geb-spock-reports#16]
Checked out the project to run the sample code and see how it all works.  Really liking the looks of it so far, however when I wanted to test how it works with screenshots I tried to run GebSampleSpec.groovy and I get this error:

```[main] INFO com.athaydes.spockframework.report.SpockReportExtension - Got configuration from Spock: com.athaydes.spockframework.report.internal.SpockReportsConfiguration([:])
[main] INFO com.athaydes.spockframework.report.internal.ConfigLoader - SpockReports config loaded: {com.athaydes.spockframework.report.showCodeBlocks=true, com.athaydes.spockframework.report.template.TemplateReportCreator.reportFileExtension=html, com.athaydes.spockframework.report.testSourceRoots=src/test/groovy, com.athaydes.spockframework.report.IReportCreator=com.athaydes.spockframework.report.template.TemplateReportCreator, com.athaydes.spockframework.report.outputDir=build/geb-spock-reports, com.athaydes.spockframework.report.internal.HtmlReportCreator.inlineCss=true, com.athaydes.spockframework.report.internal.HtmlReportCreator.featureReportCss=spock-feature-report.css, com.athaydes.spockframework.report.hideEmptyBlocks=false, com.athaydes.spockframework.report.internal.HtmlReportCreator.summaryReportCss=spock-summary-report.css, com.athaydes.spockframework.report.projectVersion=0.2.0, com.athaydes.spockframework.report.template.TemplateReportCreator.specTemplateFile=/templates/spec-template.html, com.athaydes.spockframework.report.internal.HtmlReportCreator.specSummaryNameOption=class_name_and_title, com.athaydes.spockframework.report.template.TemplateReportCreator.summaryTemplateFile=/templates/summary-template.html, com.athaydes.spockframework.report.internal.HtmlReportCreator.excludeToc=false, com.athaydes.spockframework.report.template.TemplateReportCreator.enabled=true, com.athaydes.spockframework.report.projectName=Sample Project Name, com.athaydes.spockframework.report.template.TemplateReportCreator.summaryFileName=index.html, com.athaydes.spockframework.report.internal.HtmlReportCreator.printThrowableStackTrace=false, com.athaydes.spockframework.report.internal.HtmlReportCreator.enabled=true}

Test ignored.

Test ignored.

Test ignored.

geb.driver.DriverCreationException: failed to create driver from callback 'script15472331585721226964804$_run_closure1@25aca718'

	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
	at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy:85)
	at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy)
	at geb.driver.CachingDriverFactory$SimpleCache.get(CachingDriverFactory.groovy:32)
	at geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:84)
	at geb.Configuration.createDriver(Configuration.groovy:374)
	at geb.Configuration.getDriver(Configuration.groovy:363)
	at geb.Browser.getDriver(Browser.groovy:119)
	at geb.report.PageSourceReporter.getPageSource(PageSourceReporter.groovy:42)
	at geb.report.PageSourceReporter.writePageSource(PageSourceReporter.groovy:38)
	at geb.report.PageSourceReporter.writeReport(PageSourceReporter.groovy:29)
	at geb.report.CompositeReporter.writeReport(CompositeReporter.groovy:31)
	at geb.Browser.report(Browser.groovy:980)
	at com.aoe.gebspockreports.sample.specs.GebSampleSpec.setupSpec(GebSampleSpec.groovy:24)
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at script15472331585721226964804.run_closure1(script15472331585721226964804.groovy:7)
	at script15472331585721226964804.run_closure1(script15472331585721226964804.groovy)
	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:29)
	... 13 more

[org.spockframework.runtime.RunContext.stop()] INFO com.athaydes.spockframework.report.template.TemplateReportAggregator - Writing summary report to /Users/aajac/Documents/geb-spock-reports/sample/build/geb-spock-reports/index.html

Process finished with exit code 255
```

It seems to be related to extending GebReportingSpec, because all of the other sample specs work from extending Specification.  

How does this work with screenshots if we can't use GebReportingSpec?

**Comment by jacattau** [comment]
Nevermind.  I fixed it by adding setting the system property of chromedriver in GebConfig.groovy

```
driver = {
    System.setProperty('webdriver.chrome.driver', '/path/to/chromedriver')
    new ChromeDriver() 
}
```
